Minisensor 2023 cleanup
waterloo-rocketry/cansw_sensor pull request #6
Opened 2023-05-18 02:33 UTC by BluCodeGH

2023-05-18 02:37 UTC, BluCodeGH reviewed
> Reviewed 3 of 10 files at r1, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/6)* status: all files reviewed, 1 unresolved discussion (waiting on @Darth-Raazi and @rdakhil)

___
*[`main.c` line 132 at r4](https://reviewable.io/reviews/waterloo-rocketry/cansw_sensor/6#-NVghwXg696p8DemtSan:-NVghwXg696p8DemtSao:bepvpzl) ([raw file](https://github.com/waterloo-rocketry/cansw_sensor/blob/11587d6c3329c457ffa9799774b75b15761861ca/main.c#L132)):*
> ```C
> 
>             can_msg_t sensor_msg;
>             build_analog_data_msg(millis(), SENSOR_PRESSURE_CC, pressure_4_20_psi, &sensor_msg);
> ```

Can we find some way to not hardcode the sensor IDs and which sensors are connected? Also pneumatics and CC/ox tank should probably have different configurable rates rather than one global PRES_TIME.


<!-- Sent from Reviewable.io -->

2023-10-05 02:20 UTC, JasonBrave requested changes

2023-10-05 02:20 UTC, JasonBrave commented on ICM-20948.c
> +#ifndef ICM_20948_H
Header guards should not exist in C source files

2023-10-05 02:20 UTC, JasonBrave commented on main.c
> +#define TEMP_TIME_DIFF_ms 0 // 2 Hz
Comment should reflect macro setting in the code, for this case it should be "Disabled"

2023-10-05 02:26 UTC, JasonBrave requested changes

2023-10-05 02:26 UTC, JasonBrave commented on ICM-20948.c
> +    uint8_t mag_status_2 = MY2C_read1ByteRegister(AK09916_mag_addr, ST2);
Unused variable

2023-10-05 12:26 UTC, JasonBrave commented
Lint warnings fixed

2023-10-05 12:27 UTC, JasonBrave approved these changes
LGTM

2023-10-05 12:28 UTC, merged